### ISSUE TITLE
Cancelling a job generates an HTTP 500 error

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#38]
https://test.apps.gov.bc.ca/pub/cpf/secure/ws/jobs/6818/cancel/

**Comment by pauldaustin** [comment]
The code to cancel caused a concurrent modification error on the list of groups for a job.

Added synchronized code to get the set of groups and created a new list to within that code to avoid the concurrent modification.

**Comment by mraross** [comment]
Verified in Revolsys dev environment

**Comment by mraross** [comment]
in delivery, submitted a job of 250k addresses, cancelled when it got to creating results. All jobs submitted after this didn't complete processing.

**Comment by pauldaustin** [comment]
Job ids?

Exceptions?

**Comment by pauldaustin** [comment]
The job state was actually creatingRequests not creatingResults when it was cancelled.

The code which checked to see if the job had been cancelled then cancelled any groups for that job created as part of the creatingRequests. In this case there was no group so a Null Pointer was thrown. This then caused another null pointer in the error handling code.

Both are fixed in my environment for testing.

**Comment by mraross** [comment]
Verified in prod
