### ISSUE TITLE
Structured address list - API submission

### ISSUE THREAD

**Issue by BK01** [bcgov/cpf#56]
When using the Batch Geocoder within the CPF (DLV & TEST) clients can submit a multi-request job of structured addresses successfully.

However, when trying to submit the same structured address file through the API, an error is received. Sample script for submission included below.

Batch Address List Submitter
https://bcgov.github.io/ols-devkit/als/

**Comment by pauldaustin** [comment]
Please attach the sample data to use with the python script

**Comment by pauldaustin** [comment]
User error, username and password weren't provided

**Comment by cartosmart** [comment]
[correlation_reporter_snippet.zip](https://github.com/bcgov/cpf/files/749300/correlation_reporter_snippet.zip)

Snippet test file for submitting remotely-hosted address file to batch geocoder... simplified extract from production script; echoes response from the API as follows:

<!DOCTYPE html>
<html xml:lang="en">
  <head>
    <title>500 Error</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <style>
body {
  padding-top: 50px;
}
    </style>
  </head>
  <body>
  <div class="container">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">500 Error</h3>
      </div>
      <div class="panel-body">

        <h4>I&#039;m sorry there was an error generating the page you requested.</h4>


        <button type="button" onclick="history.go(-1)" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> Back</button>
        <a type="button" href="/pub/cpf/" class="btn btn-primary btn-sm"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
      </div>
    </div>
  </div>
  </body>
</html>

**Comment by pauldaustin** [comment]
This is caused by user error.

See the Overview tab documentation for the geocoder (and other plugins).

All web services only support the HTTP POST method containing a form encoded using multipart/form-data. Parameters can be specified using query string or parameters in the form data. File uploads can only be included in the form data.

You have to force python to use multipart/form-data by including values in the files parameter. Which can also be used for non file fields.

The following syntax tells the file parameter to treat it as a normal parameter as opposed to a file.

files        = {'inputDataUrl': ('', filename)}

See the attached fixed file.

[correlation_reporter_snippet_fixed.py.txt](https://github.com/bcgov/cpf/files/750975/correlation_reporter_snippet_fixed.py.txt)

**Comment by cartosmart** [comment]
Thank you; I will confirm correct functioning of the updated client call and report it to this thread.

Curious to understand why this user error was only observed with the recent CPF/Batch Geocoder release; the identical client logic (initially provided as a sample by the development team and unchanged since) had been working without modification in all previous releases.

**Comment by pauldaustin** [comment]
The contract of the interface didn't change (it was always mutlipart/form-data). The previous version had an undocumented feature that it also accepted regular posted forms.

There was performance related enhancement that expected the request to be a MultiPart request so caused a ClassCastException.

**Comment by cmhodgson** [comment]
This approach didn't work for me; instead of:
`files        = {'inputDataUrl': ('', filename)}`
I used:
`fields['inputDataUrl'] = filename
files = {'foo': ('', 'bar')}`
Which puts the inputDataUrl in the "normal" field input but sends a fake file (foo=bar) to get Python to encode the request using multipart/form-data.

**Comment by BK01** [comment]
New Batch List Submitter tested in CPF DLV successfully with the following test cases.

1. Local file - Unstructured
2. Local file - Structured
3. Online file - Unstructured
4. Online file - Structured
