### ISSUE TITLE
failed requests in a job that completes fine in production

### ISSUE THREAD

**Issue by mraross** [bcgov/cpf#9]
Batch job 4694  in delivery has multiple failed requests whereas batch job 32568  in production has none
Same data file used for both
File below is really a .csv file.

[geocode_Vancouver.txt](https://github.com/bcgov/cpf/files/407508/geocode_Vancouver.txt)

**Comment by mraross** [comment]
Here is a file containing just a few failed addresses
[vancouver_cpf5_failures.txt](https://github.com/bcgov/cpf/files/407743/vancouver_cpf5_failures.txt)

**Comment by pauldaustin** [comment]
streetDirection=South or North not valid
 
 @AllowedValues(value = {
    "", "N", "S", "E", "W", "NW", "NE", "SW", "SE", "C"
  })
  @RequestParameter(index = 28,
      description = "(e.g., the E in 414 Gorge Rd E); valid values are N,S,E,W,NE,NW,SE,SW")
  @DefaultValue("")
  public void setStreetDirection(final String streetDirection) {
    this.query.setStreetDirection(streetDirection);
  }

**Comment by cmhodgson** [comment]
I'm guessing you're missing fields or assembling them incorrectly between reading the input values and storing or processing them? The input file doesn't include all of the input fields in the form, but it looks like some fields are being interpreted as others, in this case the civicNumber is being validated as the interpolation parameter, this is from trying a single one of the failed inputs, using the single request form:

java.lang.IllegalArgumentException: interpolation=901 not in ({adaptive=adaptive, linear=linear, none=none})
    at com.revolsys.record.schema.FieldDefinition.validate(FieldDefinition.java:769)

**Comment by mraross** [comment]
Create single request job
civicNumber=1820
streetName="E KENT"
streetType=AV
streetDirection=S
localityName=vancouver
provinceCode=BC

Submitted as batch job 4737

Get the following message in errorResult file:

  interpolation=1820 not in ({adaptive=adaptive, linear=linear, none=none})

**Comment by pauldaustin** [comment]
SOUTH and NORTH are not valid values for those fields in the BGEO plugin.

**Comment by cmhodgson** [comment]
In the previous version you didn't validate the fields of multi-request parameters, so this was allowed through, I guess that is a feature but it is a surprise. Regardless of that, Michael's example above, correcting the input to "S" or "N" and submitting a single job, results in an error.

**Comment by pauldaustin** [comment]
New version isn't deployed yet

**Comment by cmhodgson** [comment]
Sorry your resolution suggested that you had dismissed the problem as "not a problem", rather than that you had fixed it; I wanted to make sure you saw that there was still another part to the problem. I've removed the @AllowedValues from the streetDirection field locally now in the BGEO plugin, for the next delivery.

**Comment by pauldaustin** [comment]
Chris,

You said there was another issue when you had fixed the data. That other issue may have been dependent on the new version.

The AllowedValues validation remains, so if you have the annotation then it will have the drop down and enforce those values.

**Comment by cmhodgson** [comment]
By previous version I meant 4.1.4 - Michael's original problem was the north/south issue, which wasn't a problem on production, so I can only assume you weren't validating those fields (from batch input), because the single request form shows the @allowedValues. My solution to the fact that 5.0.0 now validates those fields (for batch input) is to remove the @AllowedValues restriction.

I now see that you have opened and fixed #11 in regards to Michael's further problem which is only anecdotally related. Great. Thanks. Sorry for the confusion.

**Comment by pauldaustin** [comment]
I talked with Michale about maybe in the future supporting a Map of allowed values (S,N) and labels (e.g. SOUTH,NORTH).

That way either S or South could be used.

That'd be something for 5.1.0

**Comment by mraross** [comment]
verified

**Comment by mraross** [comment]
Verified in Test

**Comment by mraross** [comment]
Verified in prod
